#:schema https://raw.githubusercontent.com/jackTabsCode/asphalt/refs/heads/main/schema.json

[creator]
type = "group"
id = 34579161

[codegen]
typescript = true
style = "nested"
strip_extensions = true

[inputs.assets]
path = "assets/asphalt/**/*"
output_path = "src/shared"

[inputs.assets.web]
"sounds/bg_beautiful_day.ogg" = { id = 1839849859 }