// This file is automatically @generated by Asphalt.
// It is not intended for manual editing.
declare const assets: {
	sounds: {
		POL_organic_thud_02: string
		alert_bad: string
		alert_dismiss: string
		alert_money: string
		alert_neutral: string
		bg_013_Another_August: string
		bg_beautiful_day: string
		bg_bugmintide: string
		bong_001: string
		boost_start: string
		boost_stop: string
		button_down: string
		button_down_alt: string
		button_up: string
		button_up_alt: string
		error_1: string
		error_2: string
		error_3: string
		explosionCrunch_003: string
		explosion_effect: string
		laser3: string
		laser_beam: string
		navigate: string
		start_game: string
		thump_sound: string
		whoosh: string
	}
	ui: {
		alert_dismiss: string
		backdrop: string
		blur: string
		button_glow_top: string
		circle: string
		diagonal_stripes: string
		heart: string
		heart_glow: string
		leader_pointer: string
		map_crosshair: string
		map_cursor: string
		menu_title: string
		nav_heart: string
		nav_heart_alt: string
		nav_home: string
		nav_home_alt: string
		nav_skins: string
		nav_skins_alt: string
		shards_icon: string
		shards_icon_color: string
		shop_button_noise: string
		shop_item_rays: string
		shop_treasure_chest: string
		skin_card_gradient: string
		skin_indicator: string
		skin_indicator_locked: string
		sunburst: string
		tile_stripes: string
		vignette: string
	}
}

export = assets