// This file is automatically @generated by Asphalt.
// It is not intended for manual editing.
declare const assets: {
	sounds: {
		POL_organic_thud_02: string
		alert_bad: string
		alert_dismiss: string
		alert_money: string
		alert_neutral: string
		bfh1_rock_falling_02: string
		bg_013_Another_August: string
		bg_beautiful_day: string
		bg_bugmintide: string
		bong_001: string
		boost_start: string
		boost_stop: string
		button_down: string
		button_down_alt: string
		button_up: string
		button_up_alt: string
		error_1: string
		error_2: string
		error_3: string
		explosionCrunch_003: string
		explosion_effect: string
		"generated-004_medium": string
		laser3: string
		laser_beam: string
		navigate: string
		start_game: string
		thump_sound: string
		whoosh: string
	}
	ui: {
		alert_dismiss: string
		backdrop: string
		blur: string
		button_glow_top: string
		clouds_bg: string
		crystals: {
			crystals_1: string
			crystals_15: string
			crystals_2: string
			crystals_25: string
			crystals_5: string
		}
		diagonal_stripes: string
		heart: string
		icons: {
			area: string
			dailyRewards: string
			kills: string
			orb: string
			rank: string
			store: string
		}
		leader_pointer: string
		menu_title: string
		patterns: {
			dots_pattern: string
			progress_content_bg: string
			progress_window_bg: string
			water_noise_pattern: string
		}
		powerups: {
			laser2: string
			nuclear: string
			shield: string
			speed: string
			tower: string
		}
		shards_icon: string
		shards_icon_color: string
		shop: {
			Cash: string
			Cash100Large: string
			Cash100kLarge: string
			Cash10kLarge: string
			Cash250Large: string
			Cash500Large: string
			Close: string
			Skins: string
			shop_room_bg: string
		}
		shop_button_noise: string
		shop_item_rays: string
		skin_card_gradient: string
		skin_indicator: string
		skin_indicator_locked: string
		skulls_bg: string
		speed_spike: string
		spot_glow: string
		sunburst: string
		tile_stripes: string
		vignette: string
		world_bg: string
	}
}

export = assets