export const images: {
	readonly skins: {
		readonly soldier_eye_left: string;
		readonly soldier_eye_right: string;
		readonly soldier_no_eye: string;
		readonly soldier_main: string;
		readonly soldier_stars: string;
		readonly soldier_jelly: string;
		readonly soldier_jelly_red: string;
		readonly soldier_jelly_blue: string;
		readonly soldier_canada: string;
		readonly soldier_outlined: string;
		readonly soldier_black_ice: string;
		readonly soldier_awesome_body: string;
		readonly soldier_awesome_head: string;
		readonly soldier_stare_body: string;
		readonly soldier_stare_head: string;
		readonly soldier_vamp_body: string;
		readonly soldier_vamp_head: string;
	};
	readonly ui: {
		readonly alert_dismiss: string;
		readonly backdrop: string;
		readonly blur: string;
		readonly button_glow_top: string;
		readonly circle: string;
		readonly heart: string;
		readonly heart_glow: string;
		readonly map_crosshair: string;
		readonly map_cursor: string;
		readonly menu_title: string;
		readonly nav_skins: string;
		readonly nav_skins_alt: string;
		readonly nav_heart: string;
		readonly nav_heart_alt: string;
		readonly nav_home: string;
		readonly nav_home_alt: string;
		readonly skin_card_gradient: string;
		readonly skin_indicator: string;
		readonly skin_indicator_locked: string;
		readonly vignette: string;
		readonly tile_stripes: string;
		readonly leader_pointer: string;
	};
};
