name: Release Production

on:
    release:
        types: [released]
    workflow_dispatch:

permissions:
    contents: write
    packages: write

concurrency:
    group: prod_environment
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  lfs: true

            - name: Build places (prod)
              uses: ./.github/actions/roblox-build
              with:
                  node_env: prod

    deploy:
        runs-on: roblox-runner
        # runs-on: self-hosted # This is needed for ROBLOSECURITY, it checks the region
        environment: prod
        needs: build

        steps:
            - name: Install GH CLI
              uses: dev-hanz-ops/install-gh-cli-action@8fff9050dae2d81b38f94500d8b74ad1d1d47410 # v0.2.0

            - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

            - name: Setup Rokit
              uses: CompeyDev/setup-rokit@v0.1.2
              with:
                  token: ${{ github.token }}

            # Download the places artifacts

            - name: Download GameLobby place artifact
              uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
              with:
                  name: GameLobby

            - name: Download Game place artifact
              uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
              with:
                  name: Game

            # Deploy the places

            - name: Deploy place
              run: mantle deploy --allow-purchases --environment prod
              env:
                  ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
                  MANTLE_AWS_ACCESS_KEY_ID: ${{ secrets.MANTLE_AWS_ACCESS_KEY_ID }}
                  MANTLE_AWS_SECRET_ACCESS_KEY: ${{ secrets.MANTLE_AWS_SECRET_ACCESS_KEY }}
                  MANTLE_OPEN_CLOUD_API_KEY: ${{ secrets.MANTLE_OPEN_CLOUD_API_KEY }}
